spring:
  application:
    name: fighter-hub
  datasource:
    url: jdbc:postgresql://localhost:5432/fighter_hub
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 24h
